### ISSUE TITLE
History Graph popup cut off on edge of card

### ISSUE THREAD

**Issue by brandondb1** [ofekashery/vertical-stack-in-card#103] opened 2021-01-12 14:48 UTC
Hello, I have a thermostat, a conditional glance card, and a history graph inside a vertical stack.  Normally, when you hover over a section of the history graph, a little box pops up showing the value of the area in the graph.  This box is on top of the card in the sense that it will extend across the boundary of the card.

In the custom vertical-stack-in-card, the box pops up, but is inside of the card such that the box is cut off by the edge of the card, which means the contents are cut off and can't be read.

The popup works fine in the stock vertical stack card, and the cutting-off behaviour existed before the conditional bits were added.  I like being able to have no boundaries between the elements of this card, since they all refer to a common function, so it would be great if this could be fixed.

Custom Card:
![image](https://user-images.githubusercontent.com/54447239/104329470-ee15fa00-54ba-11eb-88b0-f93442644777.png)

Stock Card:
![image](https://user-images.githubusercontent.com/54447239/104330563-14886500-54bc-11eb-9909-fd582d3c2cd4.png)

      - 
        cards: 
          - 
            entity: climate.thermostat
            name: Temp Control
            type: thermostat
          -
            type:  conditional
            conditions:
              - entity: climate.thermostat
                state: "heat"
              - entity: switch.hvac_fan
                state: "on"
              - entity: binary_sensor.show_turbo_heat
                state: "off"
            card:
              type: glance
              entities:
                  - entity: switch.humidifier
                    icon: mdi:water-percent
                    name: Humidifier
                    show_state: false
                  - entity: switch.auxheat
                    icon: mdi:fire
                    name: Turbo Heat
                    show_state: false
          -
            type:  conditional
            conditions:
              - entity: climate.thermostat
                state: "heat"
              - entity: binary_sensor.show_turbo_heat
                state: "on"
            card:
              type: glance
              entities:
                  - entity: switch.humidifier
                    icon: mdi:water-percent
                    name: Humidifier
                    show_state: false

          - 
            entities: 
              - entity: sensor.thermostat_state
                name: "HVAC State"
            refresh_interval: 60
            type: history-graph
        type: custom:vertical-stack-in-card

**Comment by ofekashery** [comment] 2022-10-29 16:00
Duplicate of #120.

**Closed by ofekashery** 2022-10-29 16:00 UTC
