### ISSUE TITLE
Add padding to allow separation between entities

### ISSUE THREAD

**Issue by gnkarn** [ofekashery/vertical-stack-in-card#20] opened 2018-08-07 11:21 UTC
tested 006 , it is now better aligned , but no way to separate one measure from the other ,
i think what is needed is to add a CSS padding option to styling , in order to make it useful . 

Look at the picture en closed issue .

**Comment by noxhirsch** [comment] 2018-08-25 15:29
This would be great 👍

**Comment by GreenhouseAU** [comment] 2019-07-23 02:52
Would love this!

**Comment by skylartaylor** [comment] 2019-08-04 23:00
I would also love to see this happen!

**Comment by tomecki88** [comment] 2019-11-09 00:25
@ofekashery Hi, any plans to add this enhancement?

**Comment by bcutter** [comment] 2020-12-28 18:20
> 
> 
> Another use case (that would require reducing margin/padding rather than increasing it): stacking two entities cards with reduced separation so as to make the stacking seamless (with no extra whitespace in between the last entity of the top card and the first entity of the bottom card.
> 
> Why would one want to stack two entities cards (rather than have a larger single card): when the bottom card is actual conditional (it is shown/not-shown depending on state of some switch or sensor)
> 
> So ideally there would be a way to control this separation, increasing it or decreasing it depending on the need

That´s exactly what I am looking for (see https://github.com/ofekashery/vertical-stack-in-card/issues/73#issuecomment-751815318)!

**Comment by chribster** [comment] 2021-11-08 21:43
I vote +1 on some kind of border/padding between the cards i add within the vertical stack in card

**Comment by V0v1kkk** [comment] 2022-02-03 21:22
+1

**Comment by ofekashery** [comment] 2022-10-29 16:04
Duplicate of #73.

**Closed by ofekashery** 2022-10-29 16:04 UTC
Labels: enhancement
