### ISSUE TITLE
Space still very distant 

### ISSUE THREAD

**Issue by KiLiMaToS** [ofekashery/vertical-stack-in-card#117] opened 2022-01-05 13:21 UTC
I would like to reduce the space between the cards, but apart from deleting it, the cards remain very far apart.

![image](https://user-images.githubusercontent.com/64029935/148224416-114c76fc-62c2-4101-b6de-6d36e6c7f9f3.png)

I've tried with this CSS added to Style but it doesn't seem to take any of my changes.

```
type: custom:vertical-stack-in-card
title: Temperatura
style: |
  {
    background: none;
    box-shadow: none;
    padding-top: 0;
    padding-bottom: 15px;
    padding-left: 15px;
    padding-right: 15px;
  } 
cards:
  - type: custom:vertical-stack-in-card
    horizontal: true
    cards:
      - type: markdown
        content: >
          <center> <p>Esterna</p> <p> <font color='#03a9f4'> <ha-icon
          icon="mdi:sun-thermometer-outline"/></font></p> <p> {{
          states('sensor.climatizzatore_outside_temperature') }}°C </p>
          </center>
      - type: markdown
        content: >
          <center> <p>Media</p> <p> <font color='#03a9f4'> <ha-icon
          icon="mdi:thermometer-lines"/></font></p> <p> {{
          states('sensor.temperatura_media') }}°C </p> </center>
      - type: markdown
        content: >
          <center> <p>Escursione</p> <p> <font color='#03a9f4'> <ha-icon
          icon="mdi:plus-minus-variant"/></font></p> <p> {% if
          (states('sensor.escursione'), '> 0') -%} + {%- endif -%} {{
          states('sensor.escursione') }}°C </p> </center>
  - type: custom:bar-card
    entities:
      - entity: sensor.soggiorno_temperature
        name: Soggiorno
        tap_action:

.........
```

**Comment by ofekashery** [comment] 2022-10-29 15:57
Duplicate of #130.

**Closed by ofekashery** 2022-10-29 15:57 UTC
